<a href="https://colab.research.google.com/github/pksX01/AI-practice/blob/main/Self_Attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class SelfAttention(nn.Module):
    def __init__(self, d_model=2, row_dim=0, col_dim=1):
        super().__init__()
        self.row_dim = row_dim
        self.col_dim = col_dim

        self.Wq = nn.Linear(in_features=d_model, out_features=d_model, bias=False)
        self.Wk = nn.Linear(in_features=d_model, out_features=d_model, bias=False)
        self.Wv = nn.Linear(in_features=d_model, out_features=d_model, bias=False)

    def forward(self, embedddings):
        q = self.Wq(embedddings)
        k = self.Wk(embedddings)
        v = self.Wv(embedddings)
        similarity = torch.matmul(q, k.transpose(dim0=self.row_dim, dim1=self.col_dim))
        scaled_similarity = similarity/ torch.tensor(k.size(self.col_dim)**0.5)
        attention_weights = F.softmax(scaled_similarity, dim=self.col_dim)
        attention_scores = torch.matmul(attention_weights, v)
        return attention_scores

In [ ]:
encoding_matrix = torch.Tensor([[1.16, 0.23],
                                 [0.57, 1.36],
                                 [4.41, -2.16]])
encoding_matrix.shape

torch.Size([3, 2])

In [ ]:
torch.manual_seed(42)

In [ ]:
self_attention = SelfAttention(d_model=2, row_dim=0, col_dim=1)
self_attention.forward(encoding_matrix)

tensor([[1.0100, 1.0641],
        [0.2040, 0.7057],
        [3.4989, 2.2427]], grad_fn=<MmBackward0>)

In [ ]:
q = self_attention.Wq(encoding_matrix)
q

tensor([[ 0.7621, -0.0428],
        [ 1.1063,  0.7890],
        [ 1.1164, -2.1336]], grad_fn=<MmBackward0>)

In [ ]:
k = self_attention.Wk(encoding_matrix)
k

tensor([[-0.1469, -0.3038],
        [ 0.1057,  0.3685],
        [-0.9914, -2.4152]], grad_fn=<MmBackward0>)

In [ ]:
v = self_attention.Wv(encoding_matrix)
v

tensor([[ 0.6038,  0.7434],
        [-0.3502,  0.5303],
        [ 3.8695,  2.4246]], grad_fn=<MmBackward0>)

In [ ]:
torch.matmul(F.softmax(torch.matmul(q, k.transpose(dim0=0, dim1=1))/torch.tensor(2**0.5), dim=1), v)

tensor([[1.0100, 1.0641],
        [0.2040, 0.7057],
        [3.4989, 2.2427]], grad_fn=<MmBackward0>)